In [ ]:
import os, sys
import pandas as pd
import numpy as np
sys.path.append("../feature_engineering_model/modules")

from policy_E_module import compute_consistency_scores

In [11]:
df = pd.read_csv("../data_gpt_labeler/final_data_labeled_1.csv")
df_temp = df
df_temp

,Unnamed: 0,rating,text,business_name,business_category,business_description,_id,policy_label
0,0,5,My husband took me here for my birthday! The ...,Buona Sera,"['Italian restaurant', 'Restaurant']",Casual trattoria serving familiar Italian entr...,1.089786951023629e+20_1507964592497,1
1,1,4,was a great place. Now closed. Too bad. We'll...,Buona Sera,"['Italian restaurant', 'Restaurant']",Casual trattoria serving familiar Italian entr...,1.124085651879834e+20_1519880201044,1
2,2,5,"cozy, great food. love how you can sign your b...",Buona Sera,"['Italian restaurant', 'Restaurant']",Casual trattoria serving familiar Italian entr...,1.1571615809204435e+20_1490033397528,1
3,3,4,"Not your average little Italian joint, don't e...",Buona Sera,"['Italian restaurant', 'Restaurant']",Casual trattoria serving familiar Italian entr...,1.181306411818766e+20_1511165172600,1
4,4,3,Service was great and the mozzarella fritta an...,Buona Sera,"['Italian restaurant', 'Restaurant']",Casual trattoria serving familiar Italian entr...,1.1430211684992369e+20_1505179108178,1
...,...,...,...,...,...,...,...,...
9995,9995,5,"lots of poke, good rice. I like the containers...",Da Hawaiian Poke Company,['Hawaiian restaurant'],Classic poke is made with fresh local fish at ...,1.04407355020485e+20_1470779944634,1
9996,9996,4,"Fresh poke. As a result, they often run out of...",Da Hawaiian Poke Company,['Hawaiian restaurant'],Classic poke is made with fresh local fish at ...,1.0300723756620825e+20_1521379074455,1
9997,9997,5,"Delicious poke, really exceptional customer se...",Da Hawaiian Poke Company,['Hawaiian restaurant'],Classic poke is made with fresh local fish at ...,1.1093478235156239e+20_1494303133765,1
9998,9998,4,Customizable bowls and a great selection of se...,Da Hawaiian Poke Company,['Hawaiian restaurant'],Classic poke is made with fresh local fish at ...,1.0904723719864058e+20_1473592716487,1
9999,9999,5,"Modest place. No indoor seating, just a few ta...",Da Hawaiian Poke Company,['Hawaiian restaurant'],Classic poke is made with fresh local fish at ...,1.0774654960184289e+20_1509842002635,1

In [10]:
compute_consistency_scores(df_temp)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

1025    0.959231
3758    0.993754
4299    0.988740
3799    0.985257
2279    0.903088
7015    0.988941
4286    0.500000
7991    0.979441
9906    0.967788
9988    0.770565
dtype: float64